### ISSUE TITLE
This demo doesn't seem to work anymore

### ISSUE THREAD

**Issue by thekevinbrown** [craigcoles/gatsby-storybook#1]
I'm not sure what's changed, but this is what I get:

```
$ gatsby develop
success delete html and css files from previous builds — 0.009 s
success open and validate gatsby-config.js — 0.009 s
success copy gatsby files — 0.032 s
success onPreBootstrap — 0.023 s
success source and transform nodes — 0.039 s
success building schema — 0.128 s
success createLayouts — 0.040 s
success createPages — 0.001 s
success createPagesStatefully — 0.026 s
success onPreExtractQueries — 0.001 s
success update schema — 0.076 s
success extract queries from components — 0.064 s
success run graphql queries — 0.038 s
success write out page data — 0.007 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 5.669 s

error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND


  Error: Module build failed: TypeError: fileSystem.statSync is not a function
  
  - exists.js:7 module.exports
    [gatsby-storybook]/[babel-loader]/lib/utils/exists.js:7:25
  
  - resolve-rc.js:13 find
    [gatsby-storybook]/[babel-loader]/lib/resolve-rc.js:13:9
  
  - index.js:113 Object.module.exports
    [gatsby-storybook]/[babel-loader]/lib/index.js:113:132
```

I also lodged an issue here: https://github.com/gatsbyjs/gatsby/issues/4300

**Comment by craigcoles** [comment]
@blargity I will look into this at some point today, and get back to you!

**Comment by craigcoles** [comment]
Commented on the issue you raised with Gatsby, but managed to get it working using `babel-loader 7.1.1` 

gatsbyjs/gatsby#4300
